package com.example.e_commerce.constant;

public enum PermissionName {

    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_SELF_READ,
    USER_SELF_UPDATE,

    ADDRESS_READ_ALL,
    ADDRESS_READ,
    ADDRESS_CREATE,
    ADDRESS_UPDATE,
    ADDRESS_DELETE,

    PRODUCT_READ,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    PRODUCT_VARIANT_READ,
    PRODUCT_VARIANT_CREATE,
    PRODUCT_VARIANT_UPDATE,
    PRODUCT_VARIANT_DELETE,

    ATTRIBUTE_READ,
    ATTRIBUTE_CREATE,
    ATTRIBUTE_UPDATE,
    ATTRIBUTE_DELETE,

    ATTRIBUTE_VALUE_READ,
    ATTRIBUTE_VALUE_CREATE,
    ATTRIBUTE_VALUE_UPDATE,
    ATTRIBUTE_VALUE_DELETE,

    CATEGORY_READ,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    ORDER_READ,
    ORDER_CREATE,
    ORDER_UPDATE,
    ORDER_DELETE,

    ORDER_STORE_READ,
    ORDER_STORE_UPDATE,

    CART_READ,
    CART_CREATE,
    CART_UPDATE,
    CART_DELETE,

    COUPON_READ,
    COUPON_CREATE,
    COUPON_UPDATE,
    COUPON_DELETE,

    INVENTORY_READ,
    INVENTORY_UPDATE,

    REVIEW_READ,
    REVIEW_CREATE,
    REVIEW_UPDATE,
    REVIEW_DELETE,

    STORE_READ,
    STORE_CREATE,
    STORE_UPDATE,
    STORE_DELETE,

    WISHLIST_READ,
    WISHLIST_CREATE,
    WISHLIST_DELETE
}
