package com.example.e_commerce.constant;

public enum PermissionName {

    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    PRODUCT_READ,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    CATEGORY_READ,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    ORDER_READ,
    ORDER_CREATE,
    ORDER_UPDATE,
    ORDER_DELETE,

    COUPON_READ,
    COUPON_CREATE,
    COUPON_UPDATE,
    COUPON_DELETE,

    INVENTORY_READ,
    INVENTORY_UPDATE,

    REVIEW_READ,
    REVIEW_CREATE,
    REVIEW_UPDATE,
    REVIEW_DELETE,

    SHOP_READ,
    SHOP_CREATE,
    SHOP_UPDATE,
    SHOP_DELETE,

    WISHLIST_READ,
    WISHLIST_CREATE,
    WISHLIST_DELETE
}
