spring:
  application:
    name: e-commerce
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3308/e_sql}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: false
      timeout: 30000ms
      lettuce:
        pool:
          max-active: 8
  mail:
    host: smtp.gmail.com
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT:}
            client-secret: ${GOOGLE_SECRET:}
            scope:
              - email
              - profile
            redirect-uri: ${REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  cloudinary:
    cloud_name: ${CLOUD_NAME:}
    api_key: ${API_KEY:}
    api_secret: ${API_SECRET:}

jwt:
  secret: ${JWT_SECRET:5ba957e030e819566ab19fd0a9d4ba95188fa39efd4fa47b0926f92901607c26}

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: on_param
    include-binding-errors: never

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    com.example.e_commerce: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
